language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./install.sh
- chmod a+x ./build.sh
- sudo motion update || echo 'up to date'
install:
- ./install.sh
script:
- ./build.sh
